gpsTrackService:
  testKey: testVal
  
server:
  port: 8080
security:
  user:
    password: user

spring:
  activemq:
    #broker-url: tcp://localhost:61616
    broker-url: ws://localhost:61614
    user: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/gps-track-service?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
