gpsTrackService:
  testKey: testVal
  
server:
  port: 8080
security:
  user:
    password: user

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/gps-track-service?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
